// Require Express to run server and routes
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');

// Instantiate express app
const app = express();

// Serve files from dist folder generated by webpack
app.use(express.static('dist'));

app.use(cors());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

// main app data container
const trips = [];

// post route to add new trip to trips array
app.post('/create-trip', async (req, res, next) => {
  const newTrip = req.body;
  trips.push(newTrip);
  console.log('logging placesData array from app.post', trips);
  res.send(trips);
});

app.get('/all', getTrips);

function getTrips(req, res) {
  res.send(trips);
}

app.listen(
  3000,
  console.log('Travel planning app server running on port 3000')
);

exports.trips = trips;
